# -*- coding: utf-8 -*-
"""pipeline_hr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yfx146Ib3ZlFSaL4RmPmzfCwu_ZE0Kme
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

def load_data(file):   # Load CSV file into pandas dataframe.

  try:
      df = pd.read_csv(file)

      print("Data loaded successfully")
      print(f"Data head: {df.head()}")
      print(f"Shape of data: {df.shape}")
      df.info()
      print(f"data describe: {df.describe()}")

      return df
  except Exception as e:
      print("Error loading file:", e)
      return None

def handle_missing_values(df):
    ''' Handle missing values in dataset using pandas dataframe
       and returns a cleaned dataframe (df)'''
    missing_report = df.isna().sum()

    print(" Missing Values Before Handling:")
    print(missing_report)

    for col in df.columns:

        if df[col].isnull().sum() == 0:
            continue

        # Numeric columns
        if df[col].dtype.kind in 'biufc':   # it is better than int64/float64
            df[col] = df[col].fillna(df[col].median())

        # Categorical columns
        else:
            df[col] = df[col].fillna(df[col].mode()[0])

    print("\n Missing Values Handled Successfully.")

    return df, missing_report

def detect_target_col(df):

    print("Columns:", df.columns)

    target_col = input("Enter Target Column Name: ")   # manually taking target column
    return target_col

def split_data(df, target_col):

    from sklearn.model_selection import train_test_split

    X = df.drop(columns=[target_col])
    y = df[target_col]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    return X_train, X_test, y_train, y_test

def ml_models(use_smote):

    from sklearn.preprocessing import StandardScaler
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
    from sklearn.svm import SVC
    from sklearn.neighbors import KNeighborsClassifier
    from imblearn.over_sampling import SMOTE
    from collections import Counter
    from imblearn.pipeline import Pipeline

    if use_smote:
        models = {
            'logistic': Pipeline([
                ('scaler', StandardScaler()),
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('logistic', LogisticRegression(max_iter=500, solver='liblinear'))
            ]),

            'decision_tree': Pipeline([
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('decision', DecisionTreeClassifier(max_depth=10, min_samples_split=10, random_state=42))
            ]),

            'random_forest': Pipeline([
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('rf', RandomForestClassifier(n_estimators=50, max_depth=10, n_jobs=-1, random_state=42))
            ]),

            'gradient_boosting' : Pipeline([
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('gb', GradientBoostingClassifier(n_estimators=100))
            ]),

            'knn': Pipeline([
                ('scaler', StandardScaler()),
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('knn', KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree'))
            ]),

            'svc': Pipeline([
                ('scaler', StandardScaler()),
                ('smote', SMOTE(k_neighbors=5, random_state=42)),
                ('svc', SVC(kernel='linear', max_iter=1000, tol=1e-2, class_weight='balanced'))
            ])
        }

    else:
        models = {
            'logistic': Pipeline([
                ('scaler', StandardScaler()),
                ('logistic', LogisticRegression(max_iter=500, solver='liblinear'))
            ]),

            'decision_tree': Pipeline([
                ('decision', DecisionTreeClassifier(max_depth=10, min_samples_split=10, random_state=42))
            ]),

            'random_forest': Pipeline([
                ('rf', RandomForestClassifier(n_estimators=50, max_depth=10, n_jobs=-1, random_state=42))
            ]),

            'gradient_boosting' : Pipeline([
                ('gb', GradientBoostingClassifier(n_estimators=100))
            ]),

            'knn': Pipeline([
                ('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree'))
            ]),

            'svc': Pipeline([
                ('scaler', StandardScaler()),
                ('svc', SVC(kernel='linear', max_iter=1000, tol=1e-2, class_weight='balanced'))
            ])
        }

    return models

from sklearn.preprocessing import LabelEncoder

def encode_categorical(df, target_col):

    cat_cols = df.select_dtypes(include=['object']).columns

    for col in cat_cols:

        if col == target_col:
            continue

        if df[col].nunique() == 2:
            df[col] = LabelEncoder().fit_transform(df[col])
        else:
            df = pd.get_dummies(df, columns=[col], drop_first=True)

    return df

def target_count(df, target_col):
   return df[target_col].value_counts().to_dict()

def train_and_evaluate(models, X_train, X_test, y_train, y_test, df, target_col):

    best_model = None
    best_accuracy = -1
    best_name = ""
    best_report = None

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)

        if acc > best_accuracy:
            best_accuracy = acc
            best_model = model
            best_name = name
            best_report = classification_report(y_test, y_pred, output_dict=True)

    y_pred = best_model.predict(X_test)
    probs = best_model.predict_proba(X_test)[:, 1]
    cm = confusion_matrix(y_test, y_pred)

    def get_zone(p):
        if p <= 0.3:
            return "Safe Zone"
        elif p <= 0.7:
            return "Medium Risk Zone"
        else:
            return "High Risk Zone"

    # FULL DATA (IMPORTANT)
    X_full = df.drop(columns=[target_col])
    probs_full = best_model.predict_proba(X_full)[:, 1]

    full_df = df.copy()
    full_df["Probability"] = probs_full
    full_df["Zone"] = full_df["Probability"].apply(get_zone)

    return {
        "best_model": best_model,
        "best_model_name": best_name,
        "best_accuracy": best_accuracy,
        "report": best_report,
        "cm": cm,
        "full_zone_df": full_df,
        "columns": X_train.columns
    }

def run_pipeline(df, target_col):

    df, _ = handle_missing_values(df)

    df = encode_categorical(df, target_col)

    X_train, X_test, y_train, y_test = split_data(df, target_col)

    from collections import Counter
    class_counts = Counter(y_train)
    minority = min(class_counts.values())
    majority = max(class_counts.values())
    imbalance_ratio = minority / majority
    use_smote = imbalance_ratio > 0.5

    models = ml_models(use_smote)

    result = train_and_evaluate(models, X_train, X_test, y_train, y_test, df, target_col)

    return result